---

-  name: Necessary packages for Ubuntu
   when: ansible_facts['os_family'] == "Debian"
   apt:
     name:
       - nagios3
       - nagios-plugins
       - apache2
       - apache2-utils
     update_cache: yes
     state: present

- name: Enable EPEL repository in CentOS
  when: ansible_facts['os_family'] == "RedHat"
  dnf:
     name: epel-release
     state: present

- name: Necessary packages for CentOS
  when: ansible_facts['os_family'] == "RedHat"
  dnf:
    name:
      - nagios
      - nagios-plugins
      - httpd
      - httpd-tools
    state: present

- name: Enable and start Nagios service in Ubuntu
  when: ansible_facts['os_family'] == "Debian"
  service:
    name: nagios3
    enabled: yes
    state: started

- name: Enable and start Nagios service in CentOS
  when: ansible_facts['os_family'] == "RedHat"
  service:
    name: nagios
    enabled: yes
    state: started

- name: Enable and start Apache service in Ubuntu
  when: ansible_facts['os_family'] == "Debian"
  service:
    name: apache2
    enabled: yes
    state: started

- name: Enable and start Apache service in CentOS
  when: ansible_facts['os_family'] == "RedHat"
  service:
    name: httpd
    enabled: yes
    state: started

- name: Install htpasswd for Ubuntu
  apt:
    name: apache2-utils
    state: present
  when: ansible_os_family == 'Debian'
  register: htpasswd_install_ubuntu
  ignore_errors: yes

- name: Install htpasswd for CentOS
  yum:
    name: httpd-tools
    state: present
  when: ansible_os_family in ['RedHat', 'CentOS']
  register: htpasswd_install_centos
  ignore_errors: yes

- name: Fail if htpasswd installation failed
  fail:
    msg: "Failed to install htpasswd for Ubuntu or CentOS"
  when: (ansible_os_family == 'Debian' and htpasswd_install_ubuntu is failed) or 
        (ansible_os_family in ['RedHat', 'CentOS'] and htpasswd_install_centos is failed)

- name: Create Nagios username and password for Ubuntu and CentOS
  command: >
    htpasswd -b -c {{ htpasswd_file }} {{ nagios_username }} {{ nagios_password }}
  args:
    creates: "{{ htpasswd_file }}"  # Prevents re-running if the file already exists
  vars:
    htpasswd_file: >
      {% if ansible_os_family == 'Debian' %}
        /etc/nagios3/htpasswd.users
      {% else %}
        /usr/local/nagios/etc/htpasswd.users
      {% endif %}
    nagios_username: "qjltbarquilla"
    nagios_password: "sanemimegumiuzui3"
  become: yes
